//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTrackingForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public long Id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<double> Data1 { get; set; }
        public Nullable<double> Data2 { get; set; }
        public Nullable<double> Data3 { get; set; }
        public Nullable<double> Data4 { get; set; }
        public Nullable<double> Data5 { get; set; }
        public Nullable<double> Data6 { get; set; }
        public Nullable<double> Data7 { get; set; }
        public Nullable<double> Data8 { get; set; }
        public Nullable<double> Data9 { get; set; }
        public Nullable<double> Data10 { get; set; }
        public Nullable<double> Data11 { get; set; }
        public Nullable<double> Data12 { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Machines Machines { get; set; }
    }
}
