//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anasayfa
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Hakkımızda { get; set; }
        public string Hakkimizda2 { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string HaritaAdres { get; set; }
        public string Mail { get; set; }
        public string Github { get; set; }
        public string LinkedIn { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string WebSite { get; set; }
        public string SliderImage1 { get; set; }
        public string SliderImage2 { get; set; }
        public string SliderImage3 { get; set; }
    }
}
