//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asansorler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asansorler()
        {
            this.Bakimlar = new HashSet<Bakimlar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public string SeriNumarasi { get; set; }
        public Nullable<int> MaxAgirlik { get; set; }
        public Nullable<int> ToplamMotorGucu { get; set; }
        public string QrCodeImageString { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakimlar> Bakimlar { get; set; }
    }
}
