//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakimlar
    {
        public int Id { get; set; }
        public Nullable<int> AsansorId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> BakimUcreti { get; set; }
        public Nullable<System.DateTime> BakimTarihi { get; set; }
    
        public virtual Asansorler Asansorler { get; set; }
    }
}
