//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitirmeProjesiEntities1 : DbContext
    {
        public BitirmeProjesiEntities1()
            : base("name=BitirmeProjesiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anasayfa> Anasayfa { get; set; }
        public virtual DbSet<Asansorler> Asansorler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Bakimlar> Bakimlar { get; set; }
        public virtual DbSet<Adminler> Adminler { get; set; }
    }
}
