//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsansorTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Asansorler = new HashSet<Asansorler>();
        }
    
        public int Id { get; set; }
        public string ApartmanAdi { get; set; }
        public Nullable<byte> ApartmanKatSayisi { get; set; }
        public string Yetkili { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asansorler> Asansorler { get; set; }
    }
}
